[package]
name = "phaneron-plugin-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.1"
log = "0.4.17"
phaneron-plugin = { path = "../phaneron-plugin" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
